language: python
dist: xenial
python:
  - '3.8'
  - '3.9'

env: LIBGIT2=~/libgit2/_install/ LD_LIBRARY_PATH=~/libgit2/_install/lib
before_install: ./.travis.sh
install: pip install -r requirements.txt .
before_script:
- git config --global user.name "travis-test"
- git config --global user.email "travis@test.com"
script:
- python -m unittest discover gitless/tests
branches:
  only:
  - master
jobs:
  include:
  - stage: Pack snap
    addons:
      snaps:
      - name: snapcraft
        classic: true
      - name: multipass
        classic: true
        channel: beta
    env: EMPTY
    before_install: skip
    install: skip
    script: sudo snapcraft
    deploy:
      on:
        branch: master
      provider: snap
      snap: "*.snap"
      channel: edge
      skip_cleanup: true
