# obligatory fields

name: gitless
version: git
summary: A simple version control system built on top of Git
description: |
  Gitless is a version control system built on top of Git, that is easy to learn
  and use. It features a simple commit workflow, independent branches, and
  a friendly command-line interface. Because Gitless is implemented on top of
  Git, you can always fall back on Git. And your coworkers you share a repo with
  need never know that you're not a Git aficionado.


# Base snap for snapd that is based on Ubuntu 18.04
base: core18

grade: devel          # 'stable' for stable/candidate upload
confinement: devmode  # 'strict' after right plugs and slots

# 'optional' fields

apps:
  gl:
    command: bin/gl

parts:
  libgit2:
    plugin: cmake
    # https://www.pygit2.org/install.html#version-numbers
    source: https://github.com/libgit2/libgit2/archive/v1.1.0.tar.gz
    build-packages:
      - libssl-dev

  gitless-cli:
    plugin: python
    source: .
    after: [libgit2]
    # need git until https://github.com/sdg-mit/gitless/issues/176
    stage-packages:
      - git
    build-packages:
      - git
